//
// Generated file, do not edit! Created by nedtool 5.4 from messages/routeVoting/JoinProposal.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __JOINPROPOSAL_M_H
#define __JOINPROPOSAL_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../NegotiationMessage_m.h"
// }}

/**
 * Class generated from <tt>messages/routeVoting/JoinProposal.msg:20</tt> by nedtool.
 * <pre>
 * packet JoinProposal extends NegotiationMessage
 * {
 *     int platoonId;
 *     int memberSpeeds[];
 * }
 * </pre>
 */
class JoinProposal : public ::NegotiationMessage
{
  protected:
    int platoonId;
    int *memberSpeeds; // array ptr
    unsigned int memberSpeeds_arraysize;

  private:
    void copy(const JoinProposal& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const JoinProposal&);

  public:
    JoinProposal(const char *name=nullptr, short kind=0);
    JoinProposal(const JoinProposal& other);
    virtual ~JoinProposal();
    JoinProposal& operator=(const JoinProposal& other);
    virtual JoinProposal *dup() const override {return new JoinProposal(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPlatoonId() const;
    virtual void setPlatoonId(int platoonId);
    virtual void setMemberSpeedsArraySize(unsigned int size);
    virtual unsigned int getMemberSpeedsArraySize() const;
    virtual int getMemberSpeeds(unsigned int k) const;
    virtual void setMemberSpeeds(unsigned int k, int memberSpeeds);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const JoinProposal& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, JoinProposal& obj) {obj.parsimUnpack(b);}


#endif // ifndef __JOINPROPOSAL_M_H

