//
// Generated file, do not edit! Created by nedtool 5.4 from messages/CreateGapAck.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CREATEGAPACK_M_H
#define __CREATEGAPACK_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/application/platooning/messages/ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>messages/CreateGapAck.msg:22</tt> by nedtool.
 * <pre>
 * //Notifies the leader that a gap has been successfully created
 * packet CreateGapAck extends ManeuverMessage
 * {
 * }
 * </pre>
 */
class CreateGapAck : public ::ManeuverMessage
{
  protected:

  private:
    void copy(const CreateGapAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CreateGapAck&);

  public:
    CreateGapAck(const char *name=nullptr, short kind=0);
    CreateGapAck(const CreateGapAck& other);
    virtual ~CreateGapAck();
    CreateGapAck& operator=(const CreateGapAck& other);
    virtual CreateGapAck *dup() const override {return new CreateGapAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CreateGapAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CreateGapAck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CREATEGAPACK_M_H

