//
// Generated file, do not edit! Created by nedtool 5.4 from messages/CreateGap.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CREATEGAP_M_H
#define __CREATEGAP_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/application/platooning/messages/ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>messages/CreateGap.msg:26</tt> by nedtool.
 * <pre>
 * //
 * // Notifies receiver of message to increase
 * // headway from its lead in order to allow
 * // a vehicle to join in
 * //
 * packet CreateGap extends ManeuverMessage
 * {
 *     int joinerId;
 * }
 * </pre>
 */
class CreateGap : public ::ManeuverMessage
{
  protected:
    int joinerId;

  private:
    void copy(const CreateGap& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CreateGap&);

  public:
    CreateGap(const char *name=nullptr, short kind=0);
    CreateGap(const CreateGap& other);
    virtual ~CreateGap();
    CreateGap& operator=(const CreateGap& other);
    virtual CreateGap *dup() const override {return new CreateGap(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getJoinerId() const;
    virtual void setJoinerId(int joinerId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CreateGap& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CreateGap& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CREATEGAP_M_H

