//
// Generated file, do not edit! Created by nedtool 5.4 from messages/NotifyResults.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __NOTIFYRESULTS_M_H
#define __NOTIFYRESULTS_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "NegotiationMessage_m.h"
// }}

/**
 * Class generated from <tt>messages/NotifyResults.msg:20</tt> by nedtool.
 * <pre>
 * packet NotifyResults extends NegotiationMessage
 * {
 *     int result;
 *     int joinerId;
 *     int platoonId;
 * }
 * </pre>
 */
class NotifyResults : public ::NegotiationMessage
{
  protected:
    int result;
    int joinerId;
    int platoonId;

  private:
    void copy(const NotifyResults& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NotifyResults&);

  public:
    NotifyResults(const char *name=nullptr, short kind=0);
    NotifyResults(const NotifyResults& other);
    virtual ~NotifyResults();
    NotifyResults& operator=(const NotifyResults& other);
    virtual NotifyResults *dup() const override {return new NotifyResults(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getResult() const;
    virtual void setResult(int result);
    virtual int getJoinerId() const;
    virtual void setJoinerId(int joinerId);
    virtual int getPlatoonId() const;
    virtual void setPlatoonId(int platoonId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NotifyResults& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NotifyResults& obj) {obj.parsimUnpack(b);}


#endif // ifndef __NOTIFYRESULTS_M_H

