//
// Generated file, do not edit! Created by nedtool 5.4 from messages/voting/SubmitVote.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SUBMITVOTE_M_H
#define __SUBMITVOTE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../NegotiationMessage_m.h"
// }}

/**
 * Class generated from <tt>messages/voting/SubmitVote.msg:20</tt> by nedtool.
 * <pre>
 * packet SubmitVote extends NegotiationMessage
 * {
 *     //Relevant information about joiner vehicle preferences
 *     int vote;
 *     int platoonId;
 * }
 * </pre>
 */
class SubmitVote : public ::NegotiationMessage
{
  protected:
    int vote;
    int platoonId;

  private:
    void copy(const SubmitVote& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SubmitVote&);

  public:
    SubmitVote(const char *name=nullptr, short kind=0);
    SubmitVote(const SubmitVote& other);
    virtual ~SubmitVote();
    SubmitVote& operator=(const SubmitVote& other);
    virtual SubmitVote *dup() const override {return new SubmitVote(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getVote() const;
    virtual void setVote(int vote);
    virtual int getPlatoonId() const;
    virtual void setPlatoonId(int platoonId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SubmitVote& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SubmitVote& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SUBMITVOTE_M_H

