//
// Generated file, do not edit! Created by nedtool 5.4 from messages/regroupVoting/MemberExchange.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __MEMBEREXCHANGE_M_H
#define __MEMBEREXCHANGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../NegotiationMessage_m.h"
// }}

/**
 * Class generated from <tt>messages/regroupVoting/MemberExchange.msg:20</tt> by nedtool.
 * <pre>
 * packet MemberExchange extends NegotiationMessage
 * {
 *     int platoonId;
 *     int type; //Either a REQUEST, OK or ACK
 *     int idMembers[]; //The id of the members of the platoon
 *     int speedMembers[]; //The corresponding members preferred speed
 * }
 * </pre>
 */
class MemberExchange : public ::NegotiationMessage
{
  protected:
    int platoonId;
    int type;
    int *idMembers; // array ptr
    unsigned int idMembers_arraysize;
    int *speedMembers; // array ptr
    unsigned int speedMembers_arraysize;

  private:
    void copy(const MemberExchange& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MemberExchange&);

  public:
    MemberExchange(const char *name=nullptr, short kind=0);
    MemberExchange(const MemberExchange& other);
    virtual ~MemberExchange();
    MemberExchange& operator=(const MemberExchange& other);
    virtual MemberExchange *dup() const override {return new MemberExchange(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPlatoonId() const;
    virtual void setPlatoonId(int platoonId);
    virtual int getType() const;
    virtual void setType(int type);
    virtual void setIdMembersArraySize(unsigned int size);
    virtual unsigned int getIdMembersArraySize() const;
    virtual int getIdMembers(unsigned int k) const;
    virtual void setIdMembers(unsigned int k, int idMembers);
    virtual void setSpeedMembersArraySize(unsigned int size);
    virtual unsigned int getSpeedMembersArraySize() const;
    virtual int getSpeedMembers(unsigned int k) const;
    virtual void setSpeedMembers(unsigned int k, int speedMembers);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MemberExchange& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MemberExchange& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MEMBEREXCHANGE_M_H

