//
// Generated file, do not edit! Created by nedtool 5.4 from messages/pdr/PDR.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PDR_M_H
#define __PDR_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    /** message type for pdr messages */
    static const int MANEUVER_TYPE = 22345;
// }}

/**
 * Class generated from <tt>messages/pdr/PDR.msg:23</tt> by nedtool.
 * <pre>
 * // General message for an arbitrary maneuver to holds common information.
 * // Only children of this message should be initialized.
 * packet PDRMessage
 * {
 *     // id of the originator of this message
 *     int vehicleId;
 *     // id of the destination of this message
 *     int destinationId;
 *     // sumo external id of the sender
 *     string externalId;
 * }
 * </pre>
 */
class PDRMessage : public ::omnetpp::cPacket
{
  protected:
    int vehicleId;
    int destinationId;
    ::omnetpp::opp_string externalId;

  private:
    void copy(const PDRMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PDRMessage&);

  public:
    PDRMessage(const char *name=nullptr, short kind=0);
    PDRMessage(const PDRMessage& other);
    virtual ~PDRMessage();
    PDRMessage& operator=(const PDRMessage& other);
    virtual PDRMessage *dup() const override {return new PDRMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getVehicleId() const;
    virtual void setVehicleId(int vehicleId);
    virtual int getDestinationId() const;
    virtual void setDestinationId(int destinationId);
    virtual const char * getExternalId() const;
    virtual void setExternalId(const char * externalId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PDRMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PDRMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PDR_M_H

